name: Release

# do this once it works
#on:
#  push:
#    tags:
#      - "v*.*.*"

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: push-to-dockerhub
        uses: grafana/shared-workflows/actions/build-push-to-dockerhub@main
        with:
          repository: ${{ github.repository }} # or any other dockerhub repository
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |-
            "2024-test-${{ github.sha }}"
#            "latest"
